name: Build TeXLive image

on:
  push:
  workflow_dispatch:

env:
  REGISTRY:  ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      packages: write
    strategy:
      matrix:
        version: [2022, 2023, 2024]
        tag: [22.04, 24.04]
    steps:
      - uses: actions/checkout@v4
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Image metadata
        uses: docker/metadata-action@v5
        id: meta
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value=${{ matrix.tag }}-tl${{ matrix.version }}
          labels: |
            me.dusansimic.texlive-images.tag=${{ matrix.tag }}
            me.dusansimic.texlive-images.version=${{ matrix.version }}
      - name: Build and push image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            IMAGE_TAG=${{ fromJson(steps.meta.outputs.json).labels['me.dusansimic.texlive-images.tag'] }}
            TL_VERSION=${{ fromJson(steps.meta.outputs.json).labels['me.dusansimic.texlive-images.version'] }}
